# Generated by Django 6.1 on 2026-08-21 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount_pct',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=5, null=True, verbose_name='desconto (%)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_promo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='em promoção'),
        ),
        migrations.AddField(
            model_name='offer',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='preço original'),
        ),
        migrations.CreateModel(
            name='PromoSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('min_discount', models.PositiveIntegerField(default=10, help_text='Só avisa quando o desconto for igual ou maior.', verbose_name='desconto mínimo (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('last_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='última notificação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_subscriptions', to='catalog.category', verbose_name='categoria')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_subscriptions', to='catalog.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'assinatura de promoções',
                'verbose_name_plural': 'assinaturas de promoções',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('category__isnull', False), ('product__isnull', False), _connector='OR'), name='subscription_needs_scope')],
            },
        ),
    ]
