# Generated by Django 6.1 on 2026-08-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_offer_discount_pct_offer_is_promo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL da oferta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='imagem'),
        ),
    ]
